name: Actor Docker Image CI

on:
  push:
    branches: [ "actor-ci" ]
  pull_request:
    branches: [ "actor-ci" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./actor-service --file Dockerfile --tag my-image-name:$(date +%s)
